# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/todolist
#     username: [사용할 MySQL 아이디]
#     password: [사용할 MySQL 비밀번호]
#     driver-class-name: com.mysql.cj.jdbc.Driver

#   jpa:
#     database: mysql
#     database-platform: org.hibernate.dialect.MySQL5Dialect
#     show-sql: true
#     generate-ddl: true

#     hibernate:
#       ddl-auto: update
